apiVersion: v1
kind: ConfigMap
metadata:
  name: tlproducao-config
  labels:
    app: tlproducao-config
data:  
  ds_url: jdbc:mysql://mysql-svc/tlproducao?&createDatabaseIfNotExist=true
  ds_username: root
  conexao_kafka: 10.110.5.216:9092
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tlproducao-deployment
  labels:
    app: tlproducao-deployment
spec:
  selector:
    matchLabels:
      app: tlproducao
  replicas: 1
  template:
    metadata:
      labels:
        app: tlproducao
    spec:      
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
      containers:
        - name: tlproducao
          image: luisferrarezi/tlproducao:latest
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "1.0"
          ports:
            - containerPort: 8082
              name: tlproducao-port
          env:
            - name: DATASOURCE_URL   
              valueFrom :
                configMapKeyRef :
                  name : tlproducao-config
                  key :  ds_url

            - name: CONEXAO_KAFKA
              valueFrom :
                configMapKeyRef :
                  name : tlproducao-config
                  key : conexao_kafka

            - name: DATASOURCE_PASSWORD  
              valueFrom :
                secretKeyRef :
                  name : app-secrets
                  key :  ds_pass

            - name: DATASOURCE_USERNAME
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  ds_username
---
apiVersion: v1
kind: Service
metadata:
  name: tlproducao-svc
spec:
  selector:
    app: tlproducao
  ports:
  - port: 82
    targetPort: 8082
    protocol: TCP
    name: http
---    
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tlproducao-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /producao
        backend:
          service:
            name: tlproducao-svc
            port: 
              number: 82
