apiVersion: apps/v1
kind: Deployment
metadata:
  name: tlproducao-deployment
  labels:
    app: tlproducao-deployment
spec:
  selector:
    matchLabels:
      app: tlproducao
  replicas: 1
  template:
    metadata:
      labels:
        app: tlproducao
    spec:
      containers:
        - name: tlproducao
          image: tiulanchesacr.azurecr.io/tlproducao:latest  
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "1.0"                  
          ports:
            - containerPort: 8082
              name: tlproducao-port
          env:
            - name: DATASOURCE_URL   
              valueFrom :
                configMapKeyRef:
                  name: tlproducao-config
                  key: ds_url
            - name: DATASOURCE_PASSWORD  
              valueFrom:
                configMapKeyRef:
                  name: tlproducao-config
                  key: ds_pass
            - name: DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: tlproducao-config
                  key: ds_username
            - name: CONEXAO_KAFKA
              valueFrom :
                configMapKeyRef :
                  name : tlproducao-config
                  key : conexao_kafka                  
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: tlproducao-port
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: tlproducao-port
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: tlproducao-svc
spec:
  selector:
    app: tlproducao
  ports:
    - port: 8082
      targetPort: 8082
  type: LoadBalancer
